AWSTemplateFormatVersion: '2010-09-09'

Description: Create an endpoint with lambda integration in a existing API

Resources:

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: parent_resource_id
      PathPart: 'resource_name'
      RestApiId: 'api_id'
  
  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        ConnectionType: INTERNET
        IntegrationHttpMethod: GET
        PassthroughBehavior: WHEN_NO_MATCH
        Type: AWS
        Uri: !Sub 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/lambda_arn/invocations'
      ResourceId: !Ref ApiGatewayResource
      RestApiId: 'api_id'
  
  ApiGatewayModel:
    Type: AWS::ApiGateway::Model
    Properties:
      ContentType: 'application/json'
      RestApiId: 'api_id'
      Schema: {}
  
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      RestApiId: 'api_id'
  
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      Description: Lambda API Deployment
      RestApiId: 'api_id'